# import streamlit as st
# from rag.schema_expansion import get_schema_context
# from rag.schema_context_builder import get_schema_for_tables
# from core.llm_sql import generate_sql, explain_result
# from core.db import run_sql
# from core.sql_fixer import fix_sql
# from rag.intent_classifier import generate_out_of_scope_response, is_data_question
# from rag.sql_guardrail import validate_sql
# from viz.chart_planner import plan_visualization
# from viz.chart_generator import generate_chart


# st.title("AI Data Analyst")

# question = st.text_input("Ask a question about the data")

# if question:
#     try:
#         if ("NO" in is_data_question(question)):
#             message = generate_out_of_scope_response(question)
#             st.write(message)
#             st.stop()
#         tables = get_schema_context(question)
#         schema_context = get_schema_for_tables(tables)
#         sql = generate_sql(question, schema_context)
#         sql = validate_sql(sql)
#         result, error = run_sql(sql)

#         if error :
#             st.warning("SQL failed. Attempting automatic repair...")

#             for attempt in range(3):

#                 fixed_sql = fix_sql(sql, error, schema_context)

#                 result, error = run_sql(fixed_sql)

#                 if not error:
#                     sql = fixed_sql
#                     break

#                 sql = fixed_sql
        
#         if result is not None:
#             explained_result = explain_result(question,result)

#             st.write("Generated SQL:")
#             st.code(sql)
#             st.write("Result:")
#             st.dataframe(result)
#             st.write(explained_result)

#             #Visualization
#             if not result.empty:
#                 plan = plan_visualization(question, result)
#                 generate_chart(result, plan)
    
#     except ValueError as e:
#         st.error("❌ Invalid SQL generated by AI")

#         st.write("Reason:")
#         st.warning(str(e))

#         st.write("Generated SQL:")
#         st.code(sql)

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import json
import time
import random
from datetime import datetime

# ─── PAGE CONFIG ─────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="QueryMind · AI Data Analyst",
    page_icon="◈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── GLOBAL CSS ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700;800&family=JetBrains+Mono:wght@300;400;500&display=swap');

/* ── Reset & Root ── */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

:root {
  --bg:        #0a0b0f;
  --surface:   #111318;
  --border:    #1f2330;
  --accent:    #4f8ef7;
  --accent2:   #7c5cfc;
  --green:     #22d3a0;
  --orange:    #f97c3d;
  --text:      #e8eaf0;
  --muted:     #5a6075;
  --font-head: 'Syne', sans-serif;
  --font-mono: 'JetBrains Mono', monospace;
}

/* ── App Shell ── */
.stApp { background: var(--bg); color: var(--text); font-family: var(--font-head); }
.block-container { padding: 0 !important; max-width: 100% !important; }

/* ── Hide Streamlit chrome ── */
#MainMenu, footer, header { visibility: hidden; }
.stDeployButton { display: none; }
[data-testid="stToolbar"] { display: none; }

/* ── Sidebar ── */
[data-testid="stSidebar"] {
  background: var(--surface) !important;
  border-right: 1px solid var(--border);
  padding: 0;
}
[data-testid="stSidebar"] > div { padding: 0 !important; }

/* ── Scrollbar ── */
::-webkit-scrollbar { width: 4px; height: 4px; }
::-webkit-scrollbar-track { background: transparent; }
::-webkit-scrollbar-thumb { background: var(--border); border-radius: 99px; }

/* ── Inputs ── */
.stTextInput > div > div > input,
.stTextArea textarea {
  background: var(--surface) !important;
  border: 1px solid var(--border) !important;
  color: var(--text) !important;
  border-radius: 10px !important;
  font-family: var(--font-head) !important;
  font-size: 0.95rem !important;
}
.stTextInput > div > div > input:focus,
.stTextArea textarea:focus {
  border-color: var(--accent) !important;
  box-shadow: 0 0 0 3px rgba(79,142,247,0.12) !important;
}

/* ── Buttons ── */
.stButton > button {
  background: linear-gradient(135deg, var(--accent), var(--accent2)) !important;
  color: #fff !important;
  border: none !important;
  border-radius: 10px !important;
  font-family: var(--font-head) !important;
  font-weight: 600 !important;
  letter-spacing: 0.02em !important;
  padding: 0.55rem 1.4rem !important;
  transition: opacity 0.18s, transform 0.15s !important;
}
.stButton > button:hover { opacity: 0.88 !important; transform: translateY(-1px) !important; }
.stButton > button:active { transform: translateY(0) !important; }

/* ── Dataframe ── */
[data-testid="stDataFrame"] { border-radius: 12px; overflow: hidden; }
.dvn-scroller { background: var(--surface) !important; }

/* ── Expander ── */
.streamlit-expanderHeader {
  background: var(--surface) !important;
  border: 1px solid var(--border) !important;
  border-radius: 10px !important;
  color: var(--text) !important;
  font-family: var(--font-head) !important;
}
.streamlit-expanderContent {
  background: var(--surface) !important;
  border: 1px solid var(--border) !important;
  border-top: none !important;
  border-radius: 0 0 10px 10px !important;
}

/* ── Tabs ── */
.stTabs [data-baseweb="tab-list"] {
  background: transparent !important;
  border-bottom: 1px solid var(--border) !important;
  gap: 4px;
}
.stTabs [data-baseweb="tab"] {
  background: transparent !important;
  color: var(--muted) !important;
  font-family: var(--font-head) !important;
  font-size: 0.85rem !important;
  border-radius: 8px 8px 0 0 !important;
  border: none !important;
}
.stTabs [aria-selected="true"] {
  background: var(--surface) !important;
  color: var(--accent) !important;
  border-bottom: 2px solid var(--accent) !important;
}

/* ── Metric ── */
[data-testid="stMetric"] {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 1rem 1.2rem;
}
[data-testid="stMetricLabel"] { color: var(--muted) !important; font-size: 0.75rem !important; }
[data-testid="stMetricValue"] { color: var(--text) !important; font-family: var(--font-mono) !important; }
[data-testid="stMetricDelta"] { font-size: 0.78rem !important; }

/* ── Spinner ── */
.stSpinner > div { border-top-color: var(--accent) !important; }

/* ── Select / Radio ── */
.stSelectbox > div > div, .stMultiSelect > div > div {
  background: var(--surface) !important;
  border-color: var(--border) !important;
  color: var(--text) !important;
  border-radius: 10px !important;
}
</style>
""", unsafe_allow_html=True)

# ─── MOCK DATA & STATE ────────────────────────────────────────────────────────

MOCK_SCHEMA = {
    "orders": {
        "icon": "🛒",
        "columns": [
            {"name": "order_id",    "type": "INT",       "pk": True},
            {"name": "customer_id", "type": "INT",       "pk": False},
            {"name": "order_date",  "type": "DATE",      "pk": False},
            {"name": "total",       "type": "DECIMAL",   "pk": False},
            {"name": "status",      "type": "VARCHAR",   "pk": False},
            {"name": "region",      "type": "VARCHAR",   "pk": False},
        ],
        "rows": 84200,
    },
    "customers": {
        "icon": "👤",
        "columns": [
            {"name": "customer_id", "type": "INT",     "pk": True},
            {"name": "name",        "type": "VARCHAR", "pk": False},
            {"name": "email",       "type": "VARCHAR", "pk": False},
            {"name": "segment",     "type": "VARCHAR", "pk": False},
            {"name": "joined_date", "type": "DATE",    "pk": False},
            {"name": "country",     "type": "VARCHAR", "pk": False},
        ],
        "rows": 12400,
    },
    "products": {
        "icon": "📦",
        "columns": [
            {"name": "product_id", "type": "INT",       "pk": True},
            {"name": "name",       "type": "VARCHAR",   "pk": False},
            {"name": "category",   "type": "VARCHAR",   "pk": False},
            {"name": "price",      "type": "DECIMAL",   "pk": False},
            {"name": "stock",      "type": "INT",       "pk": False},
        ],
        "rows": 3800,
    },
    "order_items": {
        "icon": "🔗",
        "columns": [
            {"name": "item_id",    "type": "INT",     "pk": True},
            {"name": "order_id",   "type": "INT",     "pk": False},
            {"name": "product_id", "type": "INT",     "pk": False},
            {"name": "qty",        "type": "INT",     "pk": False},
            {"name": "unit_price", "type": "DECIMAL", "pk": False},
        ],
        "rows": 210000,
    },
}

EXAMPLE_RESPONSES = {
    "default": {
        "sql": """SELECT
    DATE_TRUNC('month', o.order_date)  AS month,
    SUM(o.total)                       AS revenue,
    COUNT(DISTINCT o.order_id)         AS orders,
    COUNT(DISTINCT o.customer_id)      AS unique_customers
FROM orders o
WHERE o.order_date >= CURRENT_DATE - INTERVAL '6 months'
GROUP BY 1
ORDER BY 1;""",
        "data": pd.DataFrame({
            "month":            ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
            "revenue":          [124500, 138200, 152800, 141600, 169300, 183700],
            "orders":           [842, 917, 1024, 958, 1137, 1243],
            "unique_customers": [620, 701, 789, 730, 862, 941],
        }),
        "chart_type": "line",
        "insight": "Revenue grew **47.6 %** over the last 6 months, accelerating in Q2. June set a new high of **$183 700** — up 8.5 % over May. Customer acquisition is tracking revenue: unique customers rose from 620 → 941 (+51.8 %). Orders-per-customer held steady near 1.32×, suggesting growth is driven by new customers rather than repeat purchases. **Recommendation:** invest in retention campaigns to lift repeat-purchase rate above 1.5×.",
    },
    "top": {
        "sql": """SELECT
    p.category,
    SUM(oi.qty * oi.unit_price) AS revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;""",
        "data": pd.DataFrame({
            "category": ["Electronics", "Apparel", "Home & Garden", "Sports", "Beauty"],
            "revenue":  [312400, 198700, 143200, 121500, 89300],
        }),
        "chart_type": "bar",
        "insight": "**Electronics** is the dominant category at $312 400 — 36 % of total revenue — nearly 1.6× the second-place **Apparel** category ($198 700). The top-3 categories together account for **77 %** of revenue, indicating high concentration. **Home & Garden** (+18 % MoM, not shown) is the fastest grower and could challenge Apparel within 2 quarters at current trajectory.",
    },
    "customer": {
        "sql": """SELECT
    segment,
    COUNT(*) AS customers,
    AVG(total_spent) AS avg_spent
FROM (
    SELECT c.segment, c.customer_id,
           SUM(o.total) AS total_spent
    FROM customers c
    LEFT JOIN orders o ON c.customer_id = o.customer_id
    GROUP BY 1, 2
) s
GROUP BY 1
ORDER BY 2 DESC;""",
        "data": pd.DataFrame({
            "segment":   ["Enterprise", "Mid-Market", "SMB", "Individual"],
            "customers": [142, 874, 3210, 8174],
            "avg_spent": [48200, 12400, 3800, 620],
        }),
        "chart_type": "scatter",
        "insight": "A classic **long-tail distribution**: Enterprise customers (142) each spend an average of **$48 200** — 78× more than Individual customers ($620). Despite being <1.2 % of the base, Enterprise generates ~34 % of total revenue. SMB is the largest segment at 3 210 customers with solid $3 800 average spend. **Churn risk is highest in SMB** — consider a dedicated success tier to protect this revenue pool.",
    },
}

def pick_response(question: str) -> dict:
    q = question.lower()
    if any(w in q for w in ["top", "best", "highest", "category", "product"]):
        return EXAMPLE_RESPONSES["top"]
    if any(w in q for w in ["customer", "segment", "user", "who"]):
        return EXAMPLE_RESPONSES["customer"]
    return EXAMPLE_RESPONSES["default"]

def make_chart(df: pd.DataFrame, chart_type: str) -> go.Figure:
    PLOT_THEME = dict(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(family="Syne, sans-serif", color="#8b90a8", size=12),
        xaxis=dict(showgrid=False, zeroline=False, color="#5a6075"),
        yaxis=dict(showgrid=True, gridcolor="#1f2330", zeroline=False, color="#5a6075"),
        margin=dict(l=10, r=10, t=10, b=10),
        legend=dict(bgcolor="rgba(0,0,0,0)", bordercolor="rgba(0,0,0,0)"),
    )
    COLORS = ["#4f8ef7", "#7c5cfc", "#22d3a0", "#f97c3d", "#f7c948"]

    cols = df.columns.tolist()
    x = cols[0]
    ys = cols[1:]

    if chart_type == "line":
        fig = go.Figure()
        for i, y in enumerate(ys):
            fig.add_trace(go.Scatter(
                x=df[x], y=df[y], name=y.replace("_", " ").title(),
                mode="lines+markers",
                line=dict(color=COLORS[i % len(COLORS)], width=2.5),
                marker=dict(size=6),
                fill="tozeroy" if i == 0 else "none",
                fillcolor=f"rgba({','.join(str(int(COLORS[i%len(COLORS)].lstrip('#')[j:j+2],16)) for j in (0,2,4))},0.07)",
            ))
    elif chart_type == "bar":
        fig = go.Figure()
        for i, y in enumerate(ys):
            fig.add_trace(go.Bar(
                x=df[x], y=df[y], name=y.replace("_", " ").title(),
                marker=dict(
                    color=COLORS[i % len(COLORS)],
                    cornerradius=6,
                ),
            ))
        fig.update_layout(barmode="group")
    elif chart_type == "scatter":
        fig = px.scatter(
            df, x=cols[1], y=cols[2],
            size=cols[1] if len(cols) > 2 else None,
            text=cols[0],
            color=cols[0],
            color_discrete_sequence=COLORS,
        )
        fig.update_traces(textposition="top center", marker=dict(sizemin=8))
    else:
        fig = go.Figure()

    fig.update_layout(**PLOT_THEME)
    return fig

# ─── SESSION STATE ────────────────────────────────────────────────────────────
if "messages" not in st.session_state:
    st.session_state.messages = []
if "history" not in st.session_state:
    st.session_state.history = []
if "input_key" not in st.session_state:
    st.session_state.input_key = 0

# ─── SIDEBAR ──────────────────────────────────────────────────────────────────
with st.sidebar:
    # Logo
    st.markdown("""
    <div style="padding:1.6rem 1.4rem 1rem; border-bottom:1px solid #1f2330;">
      <div style="font-family:'Syne',sans-serif; font-size:1.25rem; font-weight:800;
                  background:linear-gradient(135deg,#4f8ef7,#7c5cfc); -webkit-background-clip:text;
                  -webkit-text-fill-color:transparent; letter-spacing:-0.01em;">
        ◈ QueryMind
      </div>
      <div style="font-size:0.72rem; color:#5a6075; margin-top:2px; letter-spacing:0.06em; text-transform:uppercase;">
        AI Data Analyst
      </div>
    </div>
    """, unsafe_allow_html=True)

    st.markdown("""
    <div style="padding:1rem 1.4rem 0.4rem; font-size:0.7rem; letter-spacing:0.1em;
                text-transform:uppercase; color:#5a6075; font-weight:600;">
      Schema Explorer
    </div>
    """, unsafe_allow_html=True)

    for table, meta in MOCK_SCHEMA.items():
        with st.expander(f"{meta['icon']} **{table}**  ·  {meta['rows']:,} rows"):
            for col in meta["columns"]:
                pk_badge = " 🔑" if col["pk"] else ""
                st.markdown(
                    f"<div style='display:flex;justify-content:space-between;padding:3px 0;"
                    f"border-bottom:1px solid #1f2330;font-size:0.78rem;'>"
                    f"<span style='color:#e8eaf0;font-family:JetBrains Mono,monospace;'>{col['name']}{pk_badge}</span>"
                    f"<span style='color:#5a6075;font-size:0.7rem;'>{col['type']}</span>"
                    f"</div>",
                    unsafe_allow_html=True,
                )

    st.markdown("<div style='height:1.4rem'></div>", unsafe_allow_html=True)
    st.markdown("""
    <div style="padding:0 1.4rem 0.4rem; font-size:0.7rem; letter-spacing:0.1em;
                text-transform:uppercase; color:#5a6075; font-weight:600;">
      Query History
    </div>
    """, unsafe_allow_html=True)

    if not st.session_state.history:
        st.markdown("<div style='padding:0.5rem 1.4rem; color:#5a6075; font-size:0.82rem;'>No queries yet</div>",
                    unsafe_allow_html=True)
    else:
        for i, h in enumerate(reversed(st.session_state.history[-10:])):
            st.markdown(
                f"<div style='padding:0.55rem 1rem; margin:3px 8px; border-radius:8px; cursor:pointer;"
                f"background:#0a0b0f; border:1px solid #1f2330; font-size:0.78rem; color:#8b90a8;"
                f"white-space:nowrap; overflow:hidden; text-overflow:ellipsis;' "
                f"title='{h['q']}'>"
                f"<span style='color:#4f8ef7; font-family:JetBrains Mono,monospace; font-size:0.7rem;'>"
                f"#{len(st.session_state.history)-i}</span> {h['q'][:38]}{'…' if len(h['q'])>38 else ''}"
                f"</div>",
                unsafe_allow_html=True,
            )

    st.markdown("<div style='height:1rem'></div>", unsafe_allow_html=True)
    if st.button("＋  New Session", use_container_width=True):
        st.session_state.messages = []
        st.session_state.history = []
        st.rerun()

# ─── MAIN PANEL ───────────────────────────────────────────────────────────────
main = st.container()

with main:
    # Top bar
    st.markdown("""
    <div style="display:flex; align-items:center; justify-content:space-between;
                padding:1.1rem 2rem 0.9rem; border-bottom:1px solid #1f2330;
                background:#0a0b0f; position:sticky; top:0; z-index:99;">
      <div>
        <span style="font-family:'Syne',sans-serif; font-size:1.05rem; font-weight:700; color:#e8eaf0;">
          Ask your database anything
        </span>
        <span style="margin-left:0.8rem; font-size:0.72rem; color:#22d3a0; letter-spacing:0.06em;
                     background:rgba(34,211,160,0.1); padding:2px 8px; border-radius:99px;">
          ● LIVE
        </span>
      </div>
      <div style="font-size:0.75rem; color:#5a6075; font-family:'JetBrains Mono',monospace;">
        PostgreSQL · v15.2
      </div>
    </div>
    """, unsafe_allow_html=True)

    # ── Chat area ──────────────────────────────────────────────────────────────
    chat_area = st.container()

    with chat_area:
        if not st.session_state.messages:
            st.markdown("""
            <div style="text-align:center; padding:5rem 2rem 3rem;">
              <div style="font-size:2.8rem; margin-bottom:1rem;">◈</div>
              <div style="font-family:'Syne',sans-serif; font-size:1.5rem; font-weight:700;
                          color:#e8eaf0; margin-bottom:0.6rem;">
                Start with a question
              </div>
              <div style="color:#5a6075; font-size:0.9rem; max-width:420px; margin:0 auto; line-height:1.6;">
                QueryMind turns plain English into SQL, runs the query, visualises
                the results and explains what it found — instantly.
              </div>
            </div>
            """, unsafe_allow_html=True)

            # Suggestion chips
            suggestions = [
                "Show me monthly revenue for the last 6 months",
                "Which product categories generate the most revenue?",
                "Break down customers by segment and average spend",
                "What are the top 10 customers by lifetime value?",
            ]
            cols = st.columns(2)
            for i, sug in enumerate(suggestions):
                with cols[i % 2]:
                    if st.button(sug, key=f"sug_{i}", use_container_width=True):
                        st.session_state["prefill"] = sug
                        st.rerun()

        # ── Render existing messages ──────────────────────────────────────────
        for msg in st.session_state.messages:
            if msg["role"] == "user":
                st.markdown(f"""
                <div style="display:flex; justify-content:flex-end; margin:1.2rem 2rem 0.3rem;">
                  <div style="background:linear-gradient(135deg,#4f8ef7,#7c5cfc); color:#fff;
                              border-radius:16px 16px 4px 16px; padding:0.75rem 1.1rem;
                              max-width:65%; font-size:0.92rem; line-height:1.5;">
                    {msg['content']}
                  </div>
                </div>
                """, unsafe_allow_html=True)

            elif msg["role"] == "assistant":
                resp = msg["response"]

                st.markdown("""
                <div style="margin:0.3rem 2rem 1.4rem;">
                  <div style="display:flex; align-items:center; gap:0.5rem; margin-bottom:0.8rem;">
                    <div style="width:28px; height:28px; border-radius:8px;
                                background:linear-gradient(135deg,#4f8ef7,#7c5cfc);
                                display:flex; align-items:center; justify-content:center;
                                font-size:0.85rem;">◈</div>
                    <span style="font-size:0.78rem; color:#5a6075; letter-spacing:0.04em;">QueryMind</span>
                  </div>
                """, unsafe_allow_html=True)

                tabs = st.tabs(["📊 Results", "💾 SQL", "📈 Chart", "💡 Insights"])

                # Tab 1 – Results
                with tabs[0]:
                    df = resp["data"]
                    n_rows, n_cols = df.shape
                    m1, m2, m3 = st.columns(3)
                    m1.metric("Rows returned", f"{n_rows:,}")
                    m2.metric("Columns", n_cols)
                    m3.metric("Execution time", f"{random.uniform(0.04,0.3):.2f}s")
                    st.dataframe(
                        df.style.format({
                            c: "{:,.0f}" for c in df.select_dtypes("number").columns
                        }),
                        use_container_width=True,
                        hide_index=True,
                    )

                # Tab 2 – SQL
                with tabs[1]:
                    st.markdown(
                        f"""<div style="background:#111318; border:1px solid #1f2330;
                                        border-radius:12px; padding:1.1rem 1.3rem;
                                        font-family:'JetBrains Mono',monospace; font-size:0.8rem;
                                        color:#22d3a0; line-height:1.7; white-space:pre-wrap;
                                        overflow-x:auto;">{resp['sql']}</div>""",
                        unsafe_allow_html=True,
                    )
                    col1, col2 = st.columns([1, 5])
                    with col1:
                        st.button("Copy SQL", key=f"copy_{id(msg)}")

                # Tab 3 – Chart
                with tabs[2]:
                    fig = make_chart(resp["data"], resp["chart_type"])
                    st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})

                # Tab 4 – Insights
                with tabs[3]:
                    st.markdown(f"""
                    <div style="background:rgba(79,142,247,0.06); border:1px solid rgba(79,142,247,0.18);
                                border-radius:12px; padding:1.2rem 1.4rem; line-height:1.75;
                                font-size:0.9rem; color:#c8cbda;">
                      {resp['insight']}
                    </div>
                    """, unsafe_allow_html=True)

                st.markdown("</div>", unsafe_allow_html=True)

    # ── Input bar ─────────────────────────────────────────────────────────────
    st.markdown("""
    <div style="position:sticky; bottom:0; background:linear-gradient(to top,#0a0b0f 85%,transparent);
                padding:1.5rem 2rem 1.2rem;">
    """, unsafe_allow_html=True)

    prefill_val = st.session_state.pop("prefill", "")
    col_inp, col_btn = st.columns([11, 1])

    with col_inp:
        user_input = st.text_input(
            label="",
            value=prefill_val,
            placeholder="e.g.  Show me monthly revenue trends for the past 6 months …",
            key=f"input_{st.session_state.input_key}",
            label_visibility="collapsed",
        )
    with col_btn:
        send = st.button("↑", key="send_btn")

    st.markdown("""
    <div style="text-align:center; font-size:0.7rem; color:#5a6075; margin-top:0.3rem; letter-spacing:0.04em;">
      QueryMind can make mistakes — always verify critical results
    </div>
    """, unsafe_allow_html=True)

    st.markdown("</div>", unsafe_allow_html=True)

    # ── Process input ─────────────────────────────────────────────────────────
    if (send or user_input.endswith("\n")) and user_input.strip():
        question = user_input.strip().rstrip("\n")
        st.session_state.messages.append({"role": "user", "content": question})
        st.session_state.history.append({"q": question, "ts": datetime.now().isoformat()})
        st.session_state.input_key += 1

        with st.spinner(""):
            # Simulate pipeline steps with status display
            status = st.empty()
            steps = [
                ("🔍 Retrieving schema context …",     0.4),
                ("🧠 Generating SQL …",                 0.6),
                ("⚡ Executing query …",                0.5),
                ("📊 Building visualisation …",         0.4),
                ("💡 Generating insights …",            0.5),
            ]
            for label, dur in steps:
                status.markdown(
                    f"<div style='color:#5a6075; font-size:0.82rem; padding:0.2rem 2rem;'>{label}</div>",
                    unsafe_allow_html=True,
                )
                time.sleep(dur)
            status.empty()

        resp = pick_response(question)
        st.session_state.messages.append({
            "role":     "assistant",
            "content":  "",
            "response": resp,
        })
        st.rerun()